SCREEN_W, SCREEN_H = 800, 600
SCREEN_SIZE = (SCREEN_W, SCREEN_H)
GROUND_HEIGHT = SCREEN_H - 62

BG_MULTI = 2.68
PLAYER_MULTI = 2
BRICK_MULTI = 2.69
DEBRIS_MULTI = 1.5
ENEMY_MULTI = 2.5
ENEMY_SPEED = 1
COIN_MULTI = 2

FONT = 'Fixedsys.ttf'

GRAVITY = 1.0
ANTI_GRAVITY = 0.3

